#+ summary: Testing DBpedia endpoint
#+ endpoint: http://dbpedia.org/sparql
#+ tags:
#+   - dbpedia
#+ method: GET
#+ pagination: 50
#+ defaults:
#+   - type: http://dbpedia.org/ontology/Band

SELECT ?molecule ?formula
WHERE {
  ?molecule wdt:P274 ?formula .
}
LIMIT 10
