#+ summary: Returns information about a single compound
#+ endpoint: https://query.wikidata.org/bigdata/namespace/wdq/sparql

SELECT ?molecule ?moleculeLabel ?formula
WHERE
{
	?molecule wdt:P274 ?formula .
	SERVICE wikibase:label {  bd:serviceParam wikibase:language "en" . }
} 
