#+ summary: Returns basic information about a single compound 
#+ endpoint: https://query.wikidata.org/bigdata/namespace/wdq/sparql
#+ tags:
#+   - openphacts
#+ method: GET
#+ pagination: 50

SELECT ?molecule ?moleculeLabel ?formule ?smiles ?inchiKey ?inchi ?logp ?molweight
WHERE
{
	?molecule wdt:P274 ?formule
    OPTIONAL {?molecule wdt:P233 ?smiles}
    OPTIONAL {?molecule wdt:P235 ?inchiKey;
      wdt:P234 ?inchi}
    OPTIONAL {?molecule wdt:P2993 ?logp}
    OPTIONAL {?molecule wdt:P2067 ?molweight}
	SERVICE wikibase:label {  bd:serviceParam wikibase:language "en" . }
} 
