#+ summary: Testing DBpedia endpoint
#+ endpoint: http://dbpedia.org/sparql
#+ tags:
#+   - test
#+ method: GET
#+ pagination: 50

SELECT ?molecule ?formula
WHERE {
  ?molecule wdt:P274 ?formula .
}
LIMIT 10
