#+ summary: Compound information query for a given wikidata compound
#+ endpoint: https://query.wikidata.org/sparql
#+ method: GET
#+ pagination: 50
#+ tags:
#+   - wikidata
#+ defaults:
#+   - molecule: http://www.wikidata.org/entity/Q18216

PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd:  <http://www.wikidata.org/entity/>

SELECT ?moleculeLabel ?formula ?smiles ?inchikey ?inchi ?logp ?molweight
WHERE {
    ?_molecule_iri wdt:P274 ?formula .
    ?_molecule_iri rdfs:label ?moleculeLabel
    FILTER (langMatches( lang(?moleculeLabel), "EN" ) )
    OPTIONAL {?_molecule_iri wdt:P233 ?smiles .}
    OPTIONAL {?_molecule_iri wdt:P235 ?inchikey ; wdt:P234 ?inchi .}
    OPTIONAL {?_molecule_iri wdt:P2993 ?logp .}
    OPTIONAL {?_molecule_iri wdt:P2067 ?molweight .}
}
